version: '3'

services:

  database:
    image: phuctranlv/abode-module-deploy_database
    restart: always

  homevalue:
    image: phuctranlv/abode-module-deploy_homevalue
    depends_on:
      - 'database'
    command: ["/wait-for-it.sh", "database:3306", "--", "npm", "start"]
    restart: always
    ports:
      - '80:3333'
